# Generated by Django 5.0.6 on 2024-07-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="open_to_hiring",
        ),
        migrations.AddField(
            model_name="customuser",
            name="drinking_habit",
            field=models.CharField(
                choices=[
                    ("Non-drinker", "Non-drinker"),
                    ("Occasional drinker", "Occasional drinker"),
                    ("Social drinker", "Social drinker"),
                    ("Regular drinker", "Regular drinker"),
                    ("Heavy drinker", "Heavy drinker"),
                    ("Trying to quit", "Trying to quit"),
                ],
                default="Non-drinker",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="user_photos/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("High School", "High School"),
                    ("Associate's Degree", "Associate's Degree"),
                    ("Bachelor's Degree", "Bachelor's Degree"),
                    ("Master's Degree", "Master's Degree"),
                    ("Doctorate", "Doctorate"),
                    ("Professional Degree", "Professional Degree"),
                    ("Certificate", "Certificate"),
                    ("Diploma", "Diploma"),
                    ("Postdoctoral", "Postdoctoral"),
                    ("Vocational", "Vocational"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="short_reel",
            field=models.FileField(blank=True, null=True, upload_to="short_reel/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="smoking_habit",
            field=models.CharField(
                choices=[
                    ("Non-smoker", "Non-smoker"),
                    ("Occasional smoker", "Occasional smoker"),
                    ("Regular smoker", "Regular smoker"),
                    ("Heavy smoker", "Heavy smoker"),
                    ("Trying to quit", "Trying to quit"),
                ],
                default="Non-smoker",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("High School", "High School"),
                            ("Associate's Degree", "Associate's Degree"),
                            ("Bachelor's Degree", "Bachelor's Degree"),
                            ("Master's Degree", "Master's Degree"),
                            ("Doctorate", "Doctorate"),
                            ("Professional Degree", "Professional Degree"),
                            ("Certificate", "Certificate"),
                            ("Diploma", "Diploma"),
                            ("Postdoctoral", "Postdoctoral"),
                            ("Vocational", "Vocational"),
                        ],
                        max_length=25,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="user_images/"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("address_line_1", models.TextField(max_length=250)),
                ("address_line_2", models.TextField(max_length=250)),
                ("address_line_3", models.TextField(max_length=250)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("India", "India"),
                            ("United States", "United States"),
                            ("United Kingdom", "United Kingdom"),
                            ("Australia", "Australia"),
                            ("Canada", "Canada"),
                            ("New Zealand", "New Zealand"),
                            ("Afghanistan", "Afghanistan"),
                        ],
                        default="India",
                        max_length=50,
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=25)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("is_default", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserHobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "hobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.hobby"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "hobby")},
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.interest"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "interest")},
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.skill"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "skill")},
            },
        ),
    ]
