# Generated by Django 5.0.6 on 2024-07-01 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_hobby_interest_skill_remove_customuser_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hobby",
            old_name="name",
            new_name="hobby",
        ),
    ]
