# Generated by Django 5.0.6 on 2024-07-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_industry_jobtitle_company_jobportalprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobportalprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.company",
            ),
        ),
        migrations.AlterField(
            model_name="jobportalprofile",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Kochi", "Kochi"),
                    ("Kozhikode", "Kozhikode"),
                    ("Thrissur", "Thrissur"),
                    ("Kollam", "Kollam"),
                    ("Alappuzha", "Alappuzha"),
                    ("Kannur", "Kannur"),
                    ("Palakkad", "Palakkad"),
                    ("Kottayam", "Kottayam"),
                    ("Malappuram", "Malappuram"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Idukki", "Idukki"),
                    ("Wayanad", "Wayanad"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
