# Generated by Django 5.0.6 on 2024-07-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_jobportalprofile_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="industry",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="jobtitle",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_description", models.TextField(blank=True, null=True)),
                ("salary", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Kochi", "Kochi"),
                            ("Kozhikode", "Kozhikode"),
                            ("Thrissur", "Thrissur"),
                            ("Kollam", "Kollam"),
                            ("Alappuzha", "Alappuzha"),
                            ("Kannur", "Kannur"),
                            ("Palakkad", "Palakkad"),
                            ("Kottayam", "Kottayam"),
                            ("Malappuram", "Malappuram"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Idukki", "Idukki"),
                            ("Wayanad", "Wayanad"),
                        ],
                        max_length=100,
                    ),
                ),
                ("expected_joining_date", models.DateField(blank=True, null=True)),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.jobtitle"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.jobportalprofile",
                    ),
                ),
            ],
        ),
    ]
