# Generated by Django 5.0.6 on 2024-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_job_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salary",
        ),
        migrations.AddField(
            model_name="job",
            name="salary_from",
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_to",
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
