# Generated by Django 5.0.6 on 2024-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_remove_job_salary_job_salary_from_job_salary_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_from",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_to",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
