# Generated by Django 5.0.6 on 2024-07-04 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_job_salary_from_alter_job_salary_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="jobportalprofile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="job",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="job",
            name="user",
        ),
        migrations.RemoveField(
            model_name="jobportalprofile",
            name="title",
        ),
        migrations.RemoveField(
            model_name="jobportalprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Industry",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="JobTitle",
        ),
        migrations.DeleteModel(
            name="JobPortalProfile",
        ),
    ]
