# Generated by Django 5.0.6 on 2024-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_customuser_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userskill",
            name="level",
        ),
        migrations.AlterField(
            model_name="hobby",
            name="hobby",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
