# Generated by Django 5.0.6 on 2024-07-04 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0010_remove_company_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.industry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPortalProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expertise_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Kochi", "Kochi"),
                            ("Kozhikode", "Kozhikode"),
                            ("Thrissur", "Thrissur"),
                            ("Kollam", "Kollam"),
                            ("Alappuzha", "Alappuzha"),
                            ("Kannur", "Kannur"),
                            ("Palakkad", "Palakkad"),
                            ("Kottayam", "Kottayam"),
                            ("Malappuram", "Malappuram"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Idukki", "Idukki"),
                            ("Wayanad", "Wayanad"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "job_profile",
                    models.CharField(
                        choices=[
                            ("Job Seeker", "Job Seeker"),
                            ("Employee", "Employee"),
                        ],
                        default="Job Seeker",
                        max_length=12,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.company",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_description", models.TextField(blank=True, null=True)),
                ("salary_from", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Kochi", "Kochi"),
                            ("Kozhikode", "Kozhikode"),
                            ("Thrissur", "Thrissur"),
                            ("Kollam", "Kollam"),
                            ("Alappuzha", "Alappuzha"),
                            ("Kannur", "Kannur"),
                            ("Palakkad", "Palakkad"),
                            ("Kottayam", "Kottayam"),
                            ("Malappuram", "Malappuram"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Idukki", "Idukki"),
                            ("Wayanad", "Wayanad"),
                        ],
                        max_length=100,
                    ),
                ),
                ("expected_joining_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobportalprofile",
                    ),
                ),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.jobtitle"
                    ),
                ),
            ],
        ),
    ]
