# Generated by Django 5.0.6 on 2024-07-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_jobapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="salary",
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
