# Generated by Django 5.0.6 on 2024-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_jobapplication_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="salary",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
