# Generated by Django 5.0.6 on 2024-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_jobapplication_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
