# Generated by Django 5.0.6 on 2024-07-16 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobportalprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.location",
            ),
        ),
    ]
