# Generated by Django 5.0.6 on 2024-07-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_alter_jobportalprofile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.ForeignKey(
                choices=[
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Kochi", "Kochi"),
                    ("Kozhikode", "Kozhikode"),
                    ("Thrissur", "Thrissur"),
                    ("Kollam", "Kollam"),
                    ("Alappuzha", "Alappuzha"),
                    ("Kannur", "Kannur"),
                    ("Palakkad", "Palakkad"),
                    ("Kottayam", "Kottayam"),
                    ("Malappuram", "Malappuram"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Idukki", "Idukki"),
                    ("Wayanad", "Wayanad"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.location",
            ),
        ),
    ]
