# Generated by Django 4.2.13 on 2024-07-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_country_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification_required',
            field=models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=20),
        ),
    ]
