# Generated by Django 4.2.13 on 2024-07-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_job_qualification_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
